### ISSUE TITLE
4.0出来了，大神能抽空适配一下么？

### ISSUE THREAD

**Issue by 812552787** [liuzhijie443/todesk-silently#2]
4.0出来了，大神能抽空适配一下么？

**Comment by bytehola** [comment]
> 4.0出来了，大神能抽空适配一下么？

4.1.1已上传。

**Comment by 812552787** [comment]
感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liuzhijie443/todesk-silently"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月26日(星期天) 下午2:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [liuzhijie443/todesk-silently] 4.0出来了，大神能抽空适配一下么？ (Issue #2)





  
4.0出来了，大神能抽空适配一下么？
  
4.1.1已上传。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 75443331** [comment]
> > 4.0出来了，大神能抽空适配一下么？
> 
> 4.1.1已上传。

4.1.1提示要过期了，大神有空帮忙重新适配一下吗？
