### ISSUE TITLE
请问这个静默运行程序是什么原理实现的

### ISSUE THREAD

**Issue by djgao234** [liuzhijie443/todesk-silently#7]
原理

**Comment by bytehola** [comment]
服务进程和GUI进程，让服务进程唤醒不了GUI就行了。

**Comment by djgao234** [comment]
能不能更新到 4.3.3 的 todesk 静默运行程序，4.3.3 还是 service 没有转成 raylink，目前 4.1.1 已经不支持远程控制了

**Comment by djgao234** [comment]
谢谢你🙏

**Comment by djgao234** [comment]
todsk4.3.3
https://wyl0205.lanzoul.com/i25in13faira
密码:52pj
